package jp.co.world.storedevelopment.logging.db;

public enum AccessDBColumnName {

	TIMESTMP, CATEGORY, USER_NAME, USER_CODE, URI, RESULT, LOGGER_NAME, LEVEL_STRING, THREAD_NAME, REFERENCE_FLAG, ARG0, ARG1, ARG2, ARG3, CALLER_FILENAME, CALLER_CLASS, CALLER_METHOD, CALLER_LINE
}
