alter table file add column output_number integer;
alter table file add column output_flag varchar;
alter table FILE add project_id bigint;

DROP TABLE IF EXISTS PROJECT;
DROP TABLE IF EXISTS OTHER_PROJECT_ACCOUNT;
DROP TABLE IF EXISTS PROJECT_OPINION;
DROP TABLE IF EXISTS PROJECT_CATEGORY;
DROP TABLE IF EXISTS PROJECT_PROGRESS;
DROP TABLE IF EXISTS PROJECT_SECTION_PROGRESS;
DROP TABLE IF EXISTS PROJECT_PAST_CONFERENCE;
DROP TABLE IF EXISTS PROJECT_NEGOTIATION;
DROP TABLE IF EXISTS PROJECT_TASK;
DROP TABLE IF EXISTS PROJECT_TASK_ACCOUNT;
DROP TABLE IF EXISTS PROJECT_READ_LATER_ACCOUNT;
DROP TABLE IF EXISTS PROJECT_PERSONAL_DEVELOP;
DROP TABLE IF EXISTS PROJECT_SWITING_ITEM_CONTROL;
DROP TABLE IF EXISTS I_PERIOD;

CREATE TABLE IF NOT EXISTS PROJECT(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "title" varchar(256) NOT NULL,
    "project_category_id" bigint NOT NULL,
    "division" varchar(256) NOT NULL,
    "open" boolean,
    "opening_date" timestamp,
    "section_suggest_date" date,
    "building_metting_date" date,
    "consensus_date" date,
    "contract_date" date,
    "office_project_progress_id" bigint,
    "negotiation_project_progress_id" bigint,
    "description" varchar(256),
    "start_date" date,
    "building_id" bigint,
    "i_shop_id" bigint,
    "shop_name" varchar(256),
    "corporation_id" bigint,
    "corporation_gp_id" bigint,
    "brand_id" bigint,
    "i_area_id" bigint,
    "i_block_id" bigint,
    "i_prefectures_id" bigint,
    "current_i_sales_agency_target_id" bigint,
    "progress_i_sales_agency_target_id" bigint,
    "action_status" varchar(256),
    "in_house_progress" varchar(256),
    "negotiation_progress" varchar(256),
    "contract_progress" varchar(256),
    "building_expected_value" varchar(256),
    "sales_prediction" varchar(256),
    "investment_discussion_target" boolean,
    "work_division" varchar(256),
    "external_release_start_date" date,
    "external_release_confirm" varchar(256),
    "stop" boolean,
    "stop_reason" varchar(256),
    "landing_project_category_id" bigint,
    "conclusion_possibility_percent" varchar,
    "landing_memo" text,
    "plan_status" varchar(256),
    "implementation_datetime" date,
    "i_period_id" bigint,
    "plan_period" varchar(256),
    "implementation_period" varchar(256),
    "i_sales_channel_id" bigint,
    "management_form" varchar(256),
    "sales_end_date" date,
    "rent_increase_decrease" varchar(256),
    "tenancy" boolean,
    "sales_expectation" float,
    "profit_rate" float,
    "tenancy_period" varchar(256),
    "other_request" varchar(256),
    "our_request" varchar(256),
    "requestor_name" varchar(256),
    "requestor_status" varchar(256),
    "operation_form" varchar(256),
    "article_review_date" date,
    "article_review_result" varchar(256),
    "article_review_result_comment" text,
    "management_date" date,
    "management_result" varchar(256),
    "management_result_comment" text,
    "investment_process_date" date,
    "investment_process_result" varchar(256),
    "investment_process_result_comment" text,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS OTHER_PROJECT_ACCOUNT(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "category" varchar(64),
    "i_account_id" bigint,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_OPINION(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "file_id" bigint,
    "category" varchar(256),
    "title" varchar(256),
    "comment" text,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_CATEGORY(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "name" varchar(256),
    "category" varchar(32),
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_PROGRESS(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "category" varchar(32),
    "priority" int,
    "code" varchar(256),
    "name" varchar(256),
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_SECTION_PROGRESS(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "category" varchar(32),
    "section" varchar(256),
    "frontage" varchar(256),
    "floor" varchar(256),
    "contract_tsubo" numeric,
    "business_hours" varchar(256),
    "memo" text,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_PLAN(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "category" varchar,
    "start_date"date,
    "end_date"date,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_CONTRACT_PROGRESS(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "form" varchar(256),
    "category" varchar(64),
	"contract_target_name" varchar(256),
    "contract_start_date" date,
    "contract_end_date" date,
    "contract_number_of_year" int,
    "auto_update" boolean,
    "memo" text,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_PAST_CONFERENCE(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "name" varchar(256),
    "schedule_date" date,
    "result" varchar(256),
    "attendees" varchar(256),
    "comment" varchar(256),
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_NEGOTIATION(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint NOT NULL,
    "negotiation_id" bigint NOT NULL,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_TASK(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint NOT NULL,
    "period" timestamp NOT NULL,
    "important" boolean NOT NULL,
    "complete" boolean,
    "comment" text NOT NULL,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_TASK_OWNER(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_task_id" bigint NOT NULL,
    "i_account_id" bigint NOT NULL,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_TASK_ACCOUNT(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_task_id" bigint NOT NULL,
    "account_id" bigint NOT NULL,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_READ_LATER_ACCOUNT(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint NOT NULL,
    "account_id" bigint NOT NULL,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_PERSONAL_DEVELOP(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint NOT NULL,
    "account_id" bigint NOT NULL,
    "category" varchar(64) NOT NULL,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_SWITING_ITEM_CONTROL(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "category" varchar(64) NOT NULL,
    "title" boolean NOT NULL,
    "open_information" boolean NOT NULL,
    "description" boolean NOT NULL,
    "start_datetime" boolean NOT NULL,
    "building_id" boolean NOT NULL,
    "building_area" boolean NOT NULL,
    "building_block" boolean NOT NULL,
    "building_shop_name" boolean NOT NULL,
    "building_brand" boolean NOT NULL,
    "business_name" boolean NOT NULL,
    "ground_floor" boolean NOT NULL,
    "i_sales_agency_target_id" boolean NOT NULL,
    "participating_store_corporation_id" boolean NOT NULL,
    "responsible_store_developer" boolean NOT NULL,
    "responsible_branch_store" boolean NOT NULL,
    "responsible_participating_store" boolean NOT NULL,
    "responsible_human_resource_leader" boolean NOT NULL,
    "in_house_progress" boolean NOT NULL,
    "negotiation_progress" boolean NOT NULL,
    "contract_progress" boolean NOT NULL,
    "external_release" boolean NOT NULL,
    "external_release_start_date" boolean NOT NULL,
    "external_release_confirm" boolean NOT NULL,
    "action_status" boolean NOT NULL,
    "action_schedule" boolean NOT NULL,
    "article_review_datetime" boolean NOT NULL,
    "article_review_result" boolean NOT NULL,
    "management_datetime" boolean NOT NULL,
    "management_result" boolean NOT NULL,
    "investment_process_datetime" boolean NOT NULL,
    "investment_process_result" boolean NOT NULL,
    "investment_process_result_comment" boolean NOT NULL,
    "contract_update" boolean NOT NULL,
    "economy_condition" boolean NOT NULL,
    "tenancy" boolean NOT NULL,
    "again_contract_start_date" boolean NOT NULL,
    "again_contract_end_date" boolean NOT NULL,
    "transfer_division" boolean NOT NULL,
    "transfer_tenancy" boolean NOT NULL,
    "transfer_request" boolean NOT NULL,
    "transfer_implementation_year_month" boolean NOT NULL,
    "transfer_implementation_day" boolean NOT NULL,
    "transfer_possibility" boolean NOT NULL,
    "transfer_period" boolean NOT NULL,
    "opening_store_form" boolean NOT NULL,
    "opening_store_section" boolean NOT NULL,
    "opening_store_sales_division" boolean NOT NULL,
    "opening_store_adopt_difficulty" boolean NOT NULL,
    "opening_store_corporation_name" boolean NOT NULL,
    "redecoration_expect_floor" boolean NOT NULL,
    "redecoration_ground_floor" boolean NOT NULL,
    "redecoration_frontage" boolean NOT NULL,
    "redecoration_last_sales_datetime" boolean NOT NULL,
    "landing_directionality" boolean NOT NULL,
    "important_contact" boolean NOT NULL,
    "business_hours" boolean NOT NULL,
    "business_hours_change_start_date" boolean NOT NULL,
    "branch_store_opinion" boolean NOT NULL,
    "bu_opinion" boolean NOT NULL,
    "newest_plan_information" boolean NOT NULL,
    "current_contact_form" boolean NOT NULL,
    "current_contact_start_date" boolean NOT NULL,
    "current_contact_tenancy_period" boolean NOT NULL,
    "current_contact_tenancy_date" boolean NOT NULL,
    "current_contact_economy_condition" boolean NOT NULL,
    "current_contact_down_rent_date" boolean NOT NULL,
    "current_contact_history_repair" boolean NOT NULL,
    "sales_balance_of_income" boolean NOT NULL,
    "sales_area_1_month" boolean NOT NULL,
    "sales_expected_building" boolean NOT NULL,
    "sales_area_1_year" boolean NOT NULL,
    "sales_wpc_infomation" boolean NOT NULL,
    "sales_purchasing_guests_rate" boolean NOT NULL,
    "negotiation_project_approvement" boolean NOT NULL,
    "negotiation_list" boolean NOT NULL,
    "task_list" boolean NOT NULL,
    "divition_image_list" boolean NOT NULL,
    "divition_document_list" boolean NOT NULL,
    "remarks" boolean NOT NULL,
    "manpower_schema" boolean NOT NULL,
    "needfully_manpower_datetime" boolean NOT NULL,
    "needfully_manpower_number" boolean NOT NULL,
    "needfully_manpower_schedule" boolean NOT NULL,
    "sales_agency_target" boolean NOT NULL,
    "investment" boolean NOT NULL,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS I_PERIOD(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "current_term" int,
    "appropriation_date" date,
    "wpc_date" date,
    "competition_date" date,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
