CREATE TABLE IF NOT EXISTS PROJECT_HISTORY(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
	"project_id" bigint,
    "title" varchar(256) NOT NULL,
    "project_category_id" bigint NOT NULL,
    "division" varchar(256),
    "open" boolean,
    "opening_date" timestamp,
    "section_suggest_date" date,
    "building_metting_date" date,
    "consensus_date" date,
    "contract_date" date,
    "office_project_progress_id" bigint,
    "negotiation_project_progress_id" bigint,
    "description" varchar(256),
    "start_date" date,
    "building_id" bigint,
    "i_shop_id" bigint,
    "shop_name" varchar(256),
    "shop_cd" varchar(64),
    "corporation_id" bigint,
    "corporation_gp_id" bigint,
    "brand_id" bigint,
    "i_area_id" bigint,
    "i_block_id" bigint,
    "i_prefectures_id" bigint,
    "adopt_difficulty" varchar(64),
    "current_i_sales_agency_target_id" bigint,
    "progress_i_sales_agency_target_id" bigint,
    "action_status" varchar(256),
    "in_house_progress" varchar(256),
    "negotiation_progress" varchar(256),
    "contract_progress" varchar(256),
    "m_project_action_status_id" bigint,
    "building_expected_value" varchar(256),
    "sales_prediction" varchar(256),
    "investment_discussion_target" boolean,
    "work_division" varchar(256),
    "external_release_start_date" date,
    "external_release_confirm" varchar(256),
    "stop" boolean,
    "stop_reason_id" bigint,
    "landing_project_category_id" bigint,
    "conclusion_possibility_percent_id" bigint,
    "landing_memo" text,
    "plan_status" varchar(256),
    "implementation_datetime" date,
    "i_period_id" bigint,
    "plan_period" int,
    "plan_period_half" varchar(8),
    "implementation_period" varchar(256),
    "i_sales_channel_id" bigint,
    "management_form" varchar(256),
    "sales_end_date" date,
    "rent_increase_decrease" varchar(256),
    "tenancy" boolean,
    "sales_expectation" float,
    "profit_rate" float,
    "tenancy_period" varchar(256),
    "other_request" varchar(256),
    "our_request" varchar(256),
    "requestor_name" varchar(256),
    "requestor_status" varchar(256),
    "operation_form" varchar(256),
    "article_review_date" date,
    "article_review_result_id" bigint,
    "article_review_result_comment" text,
    "management_date" date,
    "management_result_id" bigint,
    "management_result_comment" text,
    "investment_process_date" date,
    "investment_process_result_id" bigint,
    "investment_process_result_comment" text,
    "operation_division" varchar(64),
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_SECTION_PROGRESS_HISTORY(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "category" varchar(32),
    "section" varchar(256),
    "frontage" varchar(256),
    "floor" varchar(256),
    "contract_tsubo" numeric,
    "business_hours" varchar(256),
    "memo" text,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_PLAN_HISTORY(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "category" varchar,
    "sales_agency_target_id" bigint,
    "start_date"date,
    "end_date"date,
    "participating_store_corporation_id" bigint,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_CONTRACT_PROGRESS_HISTORY(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "form" varchar(256),
    "category" varchar(64),
	"contract_target_name" varchar(256),
    "contract_start_date" date,
    "contract_end_date" date,
    "contract_number_of_year" int,
    "auto_update" boolean,
    "memo" text,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS OTHER_PROJECT_ACCOUNT_HISTORY(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "category" varchar(64),
    "i_account_id" bigint,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS OTHER_PROJECT_TEAM_HISTORY(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "category" varchar(64),
    "income_unit_cd" varchar(8),
    "dept_cd" varchar(8),
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_OPINION_HISTORY(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint,
    "file_id" bigint,
    "category" varchar(256),
    "title" varchar(256),
    "comment" text,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS PROJECT_SCHEDULE_HISTORY(
    "id" serial primary key,
    "corporation_group" varchar(4) NOT NULL DEFAULT '001',
    "project_id" bigint NOT NULL,
    "m_project_action_status_id" bigint NOT NULL,
    "schedule_date" date,
    "created_datetime" timestamp NOT NULL,
    "update_datetime" timestamp NOT NULL,
    "created_account_code" varchar(64) NOT NULL,
    "update_account_code" varchar(64) NOT NULL,
    "is_deleted" boolean NOT NULL DEFAULT FALSE
);
