\c store_development_dev;

ALTER TABLE SUB_ACCOUNT OWNER TO develop;
ALTER TABLE ROLE OWNER TO develop;
ALTER TABLE I_DEPT OWNER TO develop;
ALTER TABLE I_ACCOUNT OWNER TO develop;
ALTER TABLE RELATED_TASK ADD FOREIGN KEY (account_id) REFERENCES I_ACCOUNT(id);
ALTER TABLE employee OWNER TO develop;
ALTER TABLE NEGOTIATION OWNER TO develop;
ALTER TABLE NEGOTIATION_PROJECT OWNER TO develop;
ALTER TABLE NEGOTIATION_INTERVIEW_CORPORATION OWNER TO develop;
ALTER TABLE NEGOTIATION_INTERVIEW_BUILDING OWNER TO develop;
ALTER TABLE NEGOTIATION_INTERVIEW_BRAND OWNER TO develop;
ALTER TABLE NEGOTIATION_INTERVIEW_BUSINESS_CARD OWNER TO develop;
ALTER TABLE NEGOTIATION_INTERVIEW_ACCOUNT OWNER TO develop;
ALTER TABLE NEGOTIATION_NOTICE_ACCOUNT OWNER TO develop;
ALTER TABLE NEGOTIATION_COMMENT OWNER TO develop;
ALTER TABLE NEGOTIATION_READ_LATER_ACCOUNT OWNER TO develop;
ALTER TABLE NEGOTIATION_OPEN_ACCOUNT OWNER TO develop;
ALTER TABLE BUILDING OWNER TO develop;
ALTER TABLE BUILDING_TRADE_AREA OWNER TO develop;
ALTER TABLE PROJECT OWNER TO develop;
ALTER TABLE BRAND OWNER TO develop;
ALTER TABLE PM_CORPORATION OWNER TO develop;
ALTER TABLE COMPETITION OWNER TO develop;
ALTER TABLE KEYMAN OWNER TO develop;
ALTER TABLE TENANT OWNER TO develop;
ALTER TABLE BUILDING_KEYMAN OWNER TO develop;
ALTER TABLE BUILDING_PERSONAL_DEVELOP OWNER TO develop;
ALTER TABLE ACTIVATION OWNER TO develop;
ALTER TABLE SALES_TREND OWNER TO develop;
ALTER TABLE SHOP OWNER TO develop;
ALTER TABLE BUILDING_SALES OWNER TO develop;
ALTER TABLE BUILDING_TENANT OWNER TO develop;
ALTER TABLE DIVISION OWNER TO develop;
ALTER TABLE BUILDING_MEETING_HISTORY OWNER TO develop;
ALTER TABLE I_PREFECTURES OWNER TO develop;
ALTER TABLE I_COMPETITION_SALES OWNER TO develop;
ALTER TABLE I_SHOP_SALES_TREND OWNER TO develop;
ALTER TABLE I_SHOP_SALES_LATEST_ONE_YEAR OWNER TO develop;
ALTER TABLE FILE OWNER TO develop;
ALTER TABLE TODO OWNER TO develop;
ALTER TABLE I_BUSINESS_CARD OWNER TO develop;
ALTER TABLE IMPORTANT_INFORMATION OWNER TO develop;
ALTER TABLE IMPORTANT_INFORMATION_BUILDING OWNER TO develop;
ALTER TABLE IMPORTANT_INFORMATION_CORPORATION OWNER TO develop;
ALTER TABLE IMPORTANT_INFORMATION_ACCOUNT OWNER TO develop;
ALTER TABLE IMPORTANT_INFORMATION_NEGOTIATION OWNER TO develop;
ALTER TABLE RELATED_TASK OWNER TO develop;
ALTER TABLE BUILDING_TRADE_AREA OWNER TO develop;
ALTER TABLE I_SALES_CHANNEL OWNER TO develop;
ALTER TABLE I_INCOME_UNIT_LAYER OWNER TO develop;
ALTER TABLE I_BLOCK OWNER TO develop;
ALTER TABLE I_AREA OWNER TO develop;
ALTER TABLE M_CREDIT_RANK OWNER TO develop;
ALTER TABLE I_SALES_AGENCY_TARGET OWNER TO develop;
ALTER TABLE PARTICIPATING_STORE_CORPORATION OWNER TO develop;
ALTER TABLE I_CORPORATION_GROUP OWNER TO develop;
ALTER TABLE I_CORPORATION OWNER TO develop;
ALTER TABLE I_INCOME_UNIT OWNER TO develop;
ALTER TABLE I_COMPETITION OWNER TO develop;
ALTER TABLE I_COMPETITION_BR OWNER TO develop;
ALTER TABLE I_COMPETITION_SHOP_CORPORATION OWNER TO develop;
ALTER TABLE I_SHOP OWNER TO develop;
ALTER TABLE I_PLACE OWNER TO develop;
ALTER TABLE I_STATUS OWNER TO develop;
ALTER TABLE I_SALES_AGENCY OWNER TO develop;
ALTER TABLE I_SEGMENT_DIVISION OWNER TO develop;
ALTER TABLE I_STEPS_RATE_CALCULATION_DIVISION OWNER TO develop;
ALTER TABLE I_FIXED_ASSETS_DEPRECIATION_DIVISION OWNER TO develop;
ALTER TABLE I_COMPOSITE_SHOP_DIVISION OWNER TO develop;
ALTER TABLE I_SHOPPING_STREET OWNER TO develop;
ALTER TABLE I_COMPANY OWNER TO develop;
ALTER TABLE I_REMODELING_HISTORY OWNER TO develop;
ALTER TABLE I_RENT_CONDITION OWNER TO develop;
ALTER TABLE I_MARKET OWNER TO develop;
ALTER TABLE MAIL OWNER TO develop;
ALTER TABLE PUSH_NOTIFICATION_PERMIT OWNER TO develop;
ALTER TABLE SEND_RESERVE OWNER TO develop;
ALTER TABLE PUSH_NOTIFICATION_RESULT OWNER TO develop;
ALTER TABLE INVALID_DEVICE_TOKEN OWNER TO develop;
ALTER TABLE I_MD_CALENDAR OWNER TO develop;
ALTER TABLE RECENT_CHANGE OWNER TO develop;
ALTER TABLE  I_SHOP_SALES_BR OWNER TO develop;
ALTER TABLE  I_BRAND OWNER TO develop;
ALTER TABLE  I_JIS OWNER TO develop;
ALTER TABLE  I_YAKATA OWNER TO develop;
ALTER TABLE I_BUSINESS_CARD_BATCH OWNER TO develop;
ALTER TABLE M_TODO_BATCH_SETTING OWNER TO develop;

ALTER TABLE TODO ADD FOREIGN KEY (account_id) REFERENCES I_ACCOUNT(id);
-- 重要情報
ALTER TABLE IMPORTANT_INFORMATION_BUILDING ADD FOREIGN KEY (important_information_id) REFERENCES IMPORTANT_INFORMATION(id);
ALTER TABLE IMPORTANT_INFORMATION_BUILDING ADD FOREIGN KEY (building_id) REFERENCES BUILDING(id);
ALTER TABLE IMPORTANT_INFORMATION_CORPORATION ADD FOREIGN KEY (important_information_id) REFERENCES IMPORTANT_INFORMATION(id);
ALTER TABLE IMPORTANT_INFORMATION_CORPORATION ADD FOREIGN KEY (corporation_id) REFERENCES I_CORPORATION(id);
ALTER TABLE IMPORTANT_INFORMATION_NEGOTIATION ADD FOREIGN KEY (important_information_id) REFERENCES IMPORTANT_INFORMATION(id);
ALTER TABLE IMPORTANT_INFORMATION_NEGOTIATION ADD FOREIGN KEY (negotiation_id) REFERENCES NEGOTIATION(id);
ALTER TABLE IMPORTANT_INFORMATION_ACCOUNT ADD FOREIGN KEY (important_information_id) REFERENCES IMPORTANT_INFORMATION(id);
ALTER TABLE IMPORTANT_INFORMATION_ACCOUNT ADD FOREIGN KEY (account_id) REFERENCES I_ACCOUNT(id);
-- 商談_案件テーブル用
ALTER TABLE NEGOTIATION_PROJECT  ADD FOREIGN KEY (negotiation_id) REFERENCES NEGOTIATION(id);
-- テーブル未定義 ALTER TABLE NEGOTIATION_PROJECT  ADD FOREIGN KEY (project_id) REFERENCES project(id)
-- 商談_面談先_法人テーブル用
ALTER TABLE NEGOTIATION_INTERVIEW_CORPORATION ADD FOREIGN KEY (negotiation_id) REFERENCES NEGOTIATION(id);
-- テーブル未定義 ALTER TABLE NEGOTIATION_INTERVIEW_CORPORATION ADD FOREIGN KEY (corporation_id) REFERENCES company(id)
-- 商談_面談先_館テーブル用
ALTER TABLE NEGOTIATION_INTERVIEW_BUILDING ADD FOREIGN KEY (negotiation_id) REFERENCES NEGOTIATION(id);
ALTER TABLE NEGOTIATION_INTERVIEW_BUILDING ADD FOREIGN KEY (building_id) REFERENCES BUILDING(id);
-- 商談_面談先_屋号テーブル用
ALTER TABLE NEGOTIATION_INTERVIEW_BRAND ADD FOREIGN KEY (negotiation_id) REFERENCES NEGOTIATION(id);
-- テーブル未定義 ALTER TABLE NEGOTIATION_INTERVIEW_BRAND ADD FOREIGN KEY (brand_id) REFERENCES brand(id)
-- 商談_面談先_面談者テーブル用
ALTER TABLE NEGOTIATION_INTERVIEW_BUSINESS_CARD ADD FOREIGN KEY (negotiation_id) REFERENCES NEGOTIATION(id);
ALTER TABLE NEGOTIATION_INTERVIEW_BUSINESS_CARD ADD FOREIGN KEY (business_card_id) REFERENCES I_BUSINESS_CARD(id);
-- 商談_面談先_訪問者テーブル用
ALTER TABLE NEGOTIATION_INTERVIEW_ACCOUNT ADD FOREIGN KEY (negotiation_id) REFERENCES NEGOTIATION(id);
ALTER TABLE NEGOTIATION_INTERVIEW_ACCOUNT ADD FOREIGN KEY (account_id) REFERENCES I_ACCOUNT(id);
-- 商談_コメントテーブル用
ALTER TABLE NEGOTIATION_COMMENT ADD FOREIGN KEY (negotiation_id) REFERENCES negotiation(id);
-- 商談_ファイルテーブル用
ALTER TABLE FILE ADD FOREIGN KEY (negotiation_id) REFERENCES NEGOTIATION(id);
--ALTER TABLE FILE ADD FOREIGN KEY (account_id) REFERENCES account(id);
-- 商談_後で読む_既読テーブル用
ALTER TABLE NEGOTIATION_READ_LATER_ACCOUNT OWNER TO develop;
ALTER TABLE NEGOTIATION_OPEN_ACCOUNT OWNER TO develop;
-- 店舗マスター　未定義
ALTER TABLE SHOP ADD FOREIGN KEY (i_sales_agency_target_id) REFERENCES i_sales_agency_target(id);
ALTER TABLE SHOP ADD FOREIGN KEY (participating_store_corporation_id) REFERENCES participating_store_corporation(id);
--ALTER TABLE BUILDING ADD FOREIGN KEY (i_sales_channel_id) REFERENCES i_sales_channel(id);
-- ALTER TABLE BUILDING ADD FOREIGN KEY (i_block_id) REFERENCES i_block(id);
ALTER TABLE BUILDING ADD FOREIGN KEY (i_area_id) REFERENCES i_area(id);
ALTER TABLE BUILDING ADD FOREIGN KEY (i_prefectures_id) REFERENCES i_prefectures(id);
-- FOREIGN KEY FROM TABLE pm_corporation
ALTER TABLE PM_CORPORATION ADD FOREIGN KEY (building_cd) REFERENCES building(building_cd);
ALTER TABLE PM_CORPORATION ADD FOREIGN KEY (corporation_id) REFERENCES i_corporation(id);
-- FOREIGN KEY FROM TABLE building_keyman
ALTER TABLE BUILDING_KEYMAN ADD FOREIGN KEY (building_cd) REFERENCES building(building_cd);
ALTER TABLE BUILDING_KEYMAN ADD FOREIGN KEY (keyman_id) REFERENCES keyman(id);
-- FOREIGN KEY FROM TABLE building_personal_develop
ALTER TABLE BUILDING_PERSONAL_DEVELOP ADD FOREIGN KEY (building_cd) REFERENCES building(building_cd);
ALTER TABLE BUILDING_PERSONAL_DEVELOP ADD FOREIGN KEY (account_id) REFERENCES I_ACCOUNT(id);
-- FOREIGN KEY FROM TABLE activation
ALTER TABLE ACTIVATION ADD FOREIGN KEY (building_cd) REFERENCES building(building_cd);
-- FOREIGN KEY FROM TABLE sales_trend
ALTER TABLE SALES_TREND ADD FOREIGN KEY (building_cd) REFERENCES building(building_cd);
-- FOREIGN KEY FROM TABLE building_sales
ALTER TABLE BUILDING_SALES ADD FOREIGN KEY (building_cd) REFERENCES building(building_cd);
-- FOREIGN KEY FROM TABLE building_tenant
ALTER TABLE BUILDING_TENANT ADD FOREIGN KEY (building_cd) REFERENCES building(building_cd);
ALTER TABLE BUILDING_TENANT ADD FOREIGN KEY (tenant_id) REFERENCES tenant(id);
-- FOREIGN KEY FROM TABLE building_meeting_history
ALTER TABLE BUILDING_MEETING_HISTORY ADD FOREIGN KEY (building_cd) REFERENCES building(building_cd);
