\c store_development_dev;
\COPY I_CORPORATION(corporation_id,corporation_cd,corporation_name,corporation_gp_id,coordination_created_datetime,coordination_created_account_code,coordination_update_datetime,coordination_update_account_code,action)FROM 'db/csv/I_CORPORATIVE.csv' WITH CSV;

