\c store_development_dev;
\COPY I_SALES_AGENCY_TARGET(sales_agency_target_id,sales_agency_target_name,coordination_created_datetime,coordination_created_account_code,coordination_update_datetime,coordination_update_account_code,action) FROM 'db/csv/I_SALES_AGENCY_TARGET.csv' WITH CSV;
